# Generated by Django 5.0.3 on 2024-04-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0006_student_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='isAdmin',
        ),
    ]
