# Generated by Django 5.0.3 on 2024-04-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0010_alter_meal_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_meals', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess_book.student')),
            ],
        ),
    ]
