# Generated by Django 5.0.3 on 2024-04-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0013_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
