# Generated by Django 5.0.3 on 2024-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0016_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(max_length=20),
        ),
    ]
