# Generated by Django 5.0.3 on 2024-04-27 19:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0017_remove_feedback_comment_alter_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_meals', models.CharField(max_length=100)),
                ('booking_date', models.DateField(default=datetime.datetime(2024, 4, 29, 0, 38, 15, 697806))),
                ('token', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess_book.student')),
            ],
        ),
    ]
