# Generated by Django 5.0.3 on 2024-04-27 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0019_alter_bookingtoken_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_meals',
        ),
        migrations.AlterField(
            model_name='bookingtoken',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 1, 14, 41, 76984)),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_meals',
            field=models.ManyToManyField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Tea', 'Tea'), ('Dinner', 'Dinner')], to='mess_book.meal'),
        ),
    ]
