# Generated by Django 5.0.3 on 2024-04-27 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0020_remove_booking_selected_meals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtoken',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 1, 14, 57, 11734)),
        ),
    ]
