# Generated by Django 5.0.3 on 2024-04-27 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0021_alter_bookingtoken_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingtoken',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 1, 37, 10, 869817)),
        ),
    ]
