# Generated by Django 5.0.3 on 2024-04-28 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0022_alter_booking_date_alter_bookingtoken_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_no',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingtoken',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 16, 43, 24, 944020)),
        ),
    ]
