# Generated by Django 5.0.3 on 2024-05-02 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0023_student_room_no_alter_bookingtoken_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingtoken',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 16, 7, 0, 839743)),
        ),
    ]
