# Generated by Django 5.0.3 on 2024-05-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0024_booking_total_amount_alter_bookingtoken_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtoken',
            name='student',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingToken',
        ),
    ]
