# Generated by Django 5.0.3 on 2024-05-02 10:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0025_remove_bookingtoken_student_delete_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_types', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess_book.student')),
            ],
        ),
    ]
