# Generated by Django 5.0.3 on 2024-05-02 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0026_mealbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_types', models.ManyToManyField(to='mess_book.meal')),
            ],
        ),
        migrations.DeleteModel(
            name='MealBooking',
        ),
    ]
