# Generated by Django 5.0.3 on 2024-05-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0027_booking_delete_mealbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
