# Generated by Django 5.0.3 on 2024-05-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0029_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='student_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='mess_book.student'),
            preserve_default=False,
        ),
    ]
