# Generated by Django 5.0.3 on 2024-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0031_booking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
