# Generated by Django 5.0.3 on 2024-05-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_book', '0033_leaverequest_admin_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='token',
            new_name='stud_id',
        ),
    ]
