from django.urls import path
from . import views


urlpatterns = [
    path('', views.home,name='home'),
    path('login/', views.Login,name='login'),
    path('register/', views.Register,name='register'),
    path('logout/', views.Logout, name='logout'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('update_profile/<int:user_id>/', views.update_profile, name='update_profile'),
    path('update_password/<int:user_id>/', views.update_password, name='update_password'),
    path('studhome/', views.studhome,name='studhome'),
    path('more/',views.more,name='more'),
    path('mess/', views.mess,name='mess'),
    path('book_meal/<int:student_id>/', views.book_meal,name='book_meal'),
    path('complaint/<int:student_id>/', views.user_complaints,name='complaints'),
    path('bill/<int:student_id>/', views.view_bill,name='view_bill'),
    path('leave_req/', views.leave_req,name='leave_req'),
    path('attendance/', views.attendance,name='attendance'),
    path('attendance/<int:student_id>/', views.get_attendance_data, name='attendance_data'),
    path('leave_request/', views.leave_request, name='leave_request'),
    path('notifications/<int:student_id>/', views.notifications, name='notifications'),
    path('submit-feedback/<int:student_id>/', views.submit_feedback, name='submit-feedback'),
    path('bookings/<int:user_id>/',views.user_booking),
    #admin urlsview_stud_attendance
    path('admin_dashboard/',views.dashboard,name='dashboard'),
    path('users/',views.user_list,name='users_list'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('stud_attendance/', views.mark_attendance, name='stud_attendance'),
    path('meal/',views.meal,name='meal'),
    path('add_meal/',views.add_meal,name='add_meal'),
    path('get_meals/', views.get_meals, name='get_meals'),
    path('update_meal/<int:meal_id>/', views.update_meal, name='update_meal'),
    path('complaints/', views.complaints, name='complaints'),
    path('delete_complaint/<int:complaint_id>/', views.delete_complaint, name='delete_complaint'),
    path('leave_requests/', views.leave_requests, name='leave_requests'),
    path('allow-leave/<int:request_id>/', views.allow_leave, name='allow_leave'),
    path('disallow-leave/<int:request_id>/', views.disallow_leave, name='disallow_leave'),
    path('ratings/', views.display_ratings, name='ratings'),
    path('booking_count/', views.booking_count, name='booking_count'),
    path('view_attendance/', views.view_stud_attendance,name='view_attendance'),
    path('view_attendance/<int:student_id>/', views.view_attendance_data, name='view_attendance_data'),
]